Repository 2019springcse442/Cse442, pull requests merged in 2019-04, with the labels that each got.

#82 Homepage
  style.css
Labels: Sprint2, back-end, front-end

#84 Professor Profile
  Professor Profile
  ProfessorProfileTemplate.css
  ProfessorProfileTemplate.html
  database.php
  poll_result.txt
  poll_vote.php
  style.css
Labels: Sprint2, back-end, front-end

#88 Homepage navigation bar resizeable #56
  homepage.css
  homepage.php
Labels: Sprint2, enhancement, front-end, user-story

#89 Homepage Search Bar Resizeable #42
  homepage.css
Labels: Sprint2, enhancement, front-end

#90 Schedule Matching Result Block #67 #41
  ScheduleMatching.css
  ScheduleMatching.php
Labels: Sprint2, enhancement, front-end

#99 Resizable Navigation Bar #48
  Navigation.css
  Navigation.php
Labels: Sprint2, enhancement, front-end
